package writory.domain.user.exception

class UserFoundException : RuntimeException()
